-- Abid Asif
-- Question 1
SELECT 
    STAND_NAME,
    UPPER(STAND_NAME) AS STAND_UPPER,
    LOWER(STAND_NAME) AS STAND_LOWER,
    INITCAP(STAND_NAME) AS STAND_TITLE
FROM STAND_USER;

-- Question 2
SELECT  
    USER_NAME, 
    CATCHPHRASE,
    LENGTH(CATCHPHRASE) AS PHRASE_LENGTH
FROM STAND_USER
ORDER BY PHRASE_LENGTH DESC;

-- Question 3
SELECT  
    STAND_NAME, 
    SUBSTR(STAND_NAME, 1,8) AS STAND_SHORT
FROM STAND_USER;

-- Question 4
SELECT  
    STAND_NAME, 
    INSTR(STAND_NAME,'World') AS WORLD_POSITION
FROM STAND_USER;

-- Question 5
 SELECT  
    USER_NAME, 
    LPAD(POWER,8,'*') AS POWER_BAR
FROM STAND_USER;

-- Question 6
SELECT  
    USER_NAME,
    POWER, 
    ROUND(POWER,-2) AS ROUNDED_POWER,
    TRUNC(POWER,-2) AS TRUNCATED_POWER,
    MOD(POWER,300) AS POWER_MOD_300
FROM STAND_USER;

-- Question 7
SELECT  
    USER_NAME,
    NVL2(PRECISION, TO_CHAR(PRECISION), 'No Precision') AS PRECISION_STATUS
FROM STAND_USER;